config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :links, only: [ :create] do 
    collection do 
      get :top
    end
  end
  match ':in_url', to: 'links#go', via: [:get]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user, params = {})
    @user = user || User.new
    @params = params
    if @user.role.present?
      send(@user.role)
    else
      anonymous
    end
  end

  def admin
    can :manage, :all
  end

  def guest
    cannot :manage, :all
    can [:top,:create,:go], Link
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  base_url   :string           default(""), not null
#  short_url  :string           default(""), not null
#  clicks     :integer          default(0), not null
#  creator_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Link < ApplicationRecord
  validates :base_url, presence: true, uniqueness: true
  validates :short_url, presence: true, uniqueness: true
  validates :creator_id, presence: true
  belongs_to :user, foreign_key: "creator_id"

  def self.create_or_find_link(base_url, creator)
    if Link.where(base_url: base_url).any?
      Link.find_by_base_url!(base_url)
    else
      Link.create(base_url: base_url, short_url: SecureRandom.hex(3), creator_id: creator.id)
    end
  end

  def increase_clicks
    self.clicks = self.clicks + 1
    self.save
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                         :integer          not null, primary key
#  email                      :string           default(""), not null
#  encrypted_password         :string           default(""), not null
#  reset_password_token       :string
#  reset_password_sent_at     :datetime
#  remember_created_at        :datetime
#  sign_in_count              :integer          default(0), not null
#  current_sign_in_at         :datetime
#  last_sign_in_at            :datetime
#  current_sign_in_ip         :inet
#  last_sign_in_ip            :inet
#  confirmation_token         :string
#  confirmed_at               :datetime
#  confirmation_sent_at       :datetime
#  unconfirmed_email          :string
#  failed_attempts            :integer          default(0), not null
#  unlock_token               :string
#  locked_at                  :datetime
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  role                       :string           default("guest")
#  guest_authentication_token :string
#

class User < ApplicationRecord
  extend Enumerize
  validates :role, presence: true
  enumerize :role, in: [:member, :admin, :guest], default: :guest, scope: true
  has_many :links
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  before_validation :prepare_guest

  after_initialize do
    @raw_guest_authentication_token = nil
  end

  def self.build_guest(session)
    guest = User.new(role: 'guest')
    if session[:guest_authentication_token].present?
      guest.guest_authentication_token = Devise.token_generator.digest(self, :guest_authentication_token, session[:guest_authentication_token])
    else
      guest.generate_guest_authentication_token(session)
    end
    guest
  end

  def matches_guest_authentication_token?(guest_authentication_token)
    self.guest_authentication_token ==
    Devise.token_generator.digest(self.class, :guest_authentication_token, guest_authentication_token)
  end

  def self.find_by_guest_authentication_token(guest_authentication_token)
    original_token = guest_authentication_token
    guest_authentication_token = Devise.token_generator.digest(self, :guest_authentication_token, guest_authentication_token)

    where(guest_authentication_token: guest_authentication_token).first
  end

  def generate_guest_authentication_token(session)
    raw, enc = Devise.token_generator.generate(self.class, :guest_authentication_token)
    session[:guest_authentication_token] = raw
    self.guest_authentication_token = enc
  end

  protected

  def confirmation_required?
    false
  end

  def password_required?
    self.role == 'guest' ? false : super
  end

  def prepare_guest
    if self.role == 'guest'
      if self.email.blank?
        self.email = "guest_#{Time.zone.now.to_i}#{rand(100)}@guest.com"
        self.skip_confirmation!
      end
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  check_authorization unless: :devise_controller?
  protect_from_forgery with: :exception
  before_action :save_guest_user

  rescue_from CanCan::AccessDenied do |exception|
    render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
  end

   # if user is logged in, return current_user, else return guest_user
   def current_or_guest_user
    if current_user
      if session[:guest_authentication_token] &&
        !current_user.matches_guest_authentication_token?(session[:guest_authentication_token])
        # transfer_guest_to_current_user
        guest_user(with_retry = false).try(:destroy)
        session[:guest_authentication_token] = nil
      end
      current_user
    else
      guest_user
    end
  end

  # Find guest_user object associated with the current session,
  # Creating one as needed
  def guest_user(with_retry = true)
    begin
      # Cache the value the first time it's gotten.
      @cached_guest_user ||=User.find_by_guest_authentication_token(session[:guest_authentication_token]) ||User.build_guest(session)
    rescue ActiveRecord::RecordNotFound
      session[:guest_authentication_token] = nil
      guest_user if with_retry
    end
  end

  protected

  def save_guest_user
    current_or_guest_user.save
  end

  def current_ability
    @current_ability ||= Ability.new(current_or_guest_user, params)
  end

  # def transfer_guest_to_current_user
  #   logging_guest_user = guest_user(with_retry = false)
  #   if logging_guest_user
  #     logging_guest_user.takes.update_all(taker_id: current_user.id)
  #   end
  # end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  load_and_authorize_resource

  def top
    @links = Link.all.order('clicks DESC').first(10)
  end

  def create
    @link = Link.create_or_find_link(link_params[:base_url], current_or_guest_user)
    respond_to do |format|
      format.js
    end
  end

  def go
    if Link.where(short_url: params[:in_url]).any?
      @link = Link.find_by_short_url!(params[:in_url])
      @link.increase_clicks
      redirect_to @link.base_url
    else
      redirect_to root_url
      flash[:error] = "No short url found.."
    end
  end

  private

  def link_params
    params.require(:link).permit(:base_url, :short_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_authorization_check
  def home
    @link = Link.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/_flash.html.erb
<div id="flash">
  <% flash.each do |type, message| %>
    <% if message.is_a? Array %>
      <% message.each do |msg| %>
        <div class="alert alert-<%= type %>" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= msg %>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-<%= type %>" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top">
	<div class="container">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="<%= root_path %>">shortly</a>
		<div class="collapse navbar-collapse justify-content-md-center" id="navbarsExampleDefault">
			<ul class="navbar-nav mr-auto">
				<% if current_user.present? %>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
					<div class="dropdown-menu" aria-labelledby="dropdown01">
						<%= link_to edit_user_registration_path, class: "dropdown-item" do %>
						<%= t('.edit_profile') %>
						<% end %>
						<%= link_to destroy_user_session_path, :method => :delete, class: "logout dropdown-item" do %>
						<%= t('.sign_out') %>
						<% end %>
					</div>
				</li>
				<% end %>
			</ul>
			<span class="navbar-text">
				<a href="<%= top_links_path %>" class="top-link">Top links</a>
			</span>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>shortly</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<%= render partial: "layouts/header" %>
	<%= render partial: "layouts/flash" %>
	<div class="container" id="main">
		<%= yield %>
	</div>
</body>
</html>

app/views/links/_form.html.erb
<div id="link-form-wrapper">
  <%= simple_form_for link, url: links_path, remote: true do |f| %>
  <div class="input-group input-group-lg form-group url required link_base_url">
    <input type="text" class="form-control string url required" type="url" value="" name="link[base_url]" id="link_base_url" placeholder="Paste a link to shorten it" aria-label="Paste a link to shorten it">
    <span class="input-group-btn">
      <input class="btn btn-success btn-go" type="submit" value="SHORTEN">
    </span>
  </div>
  <% end %>
</div>

app/views/links/_short_link.html.erb
<div id="short-link-wrapper">
  <div class="card">
    <div class="card-header">Short link</div>
    <div class="card-body">
      <p class="card-text"><%= root_url + link.short_url %></p>
      <a href="<%= root_url + link.short_url %>" class="btn btn-primary" target="_blank" >Try it!</a>
    </div>
    <div class="card-footer text-muted">
      <a href="" class="card-link new-url-form text-right">Create another link</a>
    </div>
  </div>
</div>

app/views/links/create.js.erb
<% if @link.valid? %>
  $("#link-form-wrapper").html("<%= escape_javascript(render(partial: 'links/short_link', locals: { link: @link }))%>");
  $(".card-link.new-url-form").click(function(){
    $("#short-link-wrapper").html("<%= escape_javascript(render(partial: 'links/form', locals: { link: Link.new }))%>");
  });
<% end %>

app/views/links/top.html.erb
<div class="row">
  <div class="col-sm-12">
    <% if @links.present? %>
    <table class="table table-striped top-links-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Original Link</th>
          <th>Short Link</th>
          <th>Clicks</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @links.each_with_index do |link, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= link.base_url %></td>
          <td><%= root_url + link.short_url %></td>
          <td><%= link.clicks %></td>
          <td><a href="<%= root_url + link.short_url %>" class="btn btn-primary" target="_blank" >Visit</a></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <div class="card">
      <div class="card-block text-center">
        No links found..
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
	<div class="col-md-6 offset-md-3 text-center">
			<%= render partial: 'links/form', locals: { link: @link } %>
	</div>
</div>